#!/usr/bin/expect -f


spawn sudo apt update

spawn sudo apt install nodejs
expect "Do you want to continue?"
send -- "yes\r"

expect eof

spawn sudo apt install npm
expect "Do you want to continue?"
send -- "yes\r"



expect eof


