#!/usr/bin/expect -f


spawn sudo apt update

spawn sudo apt install nodejs
expect "Do you want to continue?"
send -- "yes\r"

sleep 2

spawn sudo apt install npm
expect "Do you want to continue?"


expect eof


